mode = "dark"

accent = "#5ee7ff"
selection = "#16455a"
muted = "#347a91"

background = "#050b0f"
dark_background = "#03080b"
darker_background = "#010405"
lighter_background = "#0f2029"

foreground = "#d6f4fc"
dark_foreground = "#4a707e"
light_foreground = "#b3e5f3"
bright_foreground = "#f0feff"

hyprland_active_border = "rgba(7df4ffff) rgba(ff9f1cff) 45deg"
hyprland_inactive_border = "rgba(11384aaa)"
active_border_color = "#5ee7ff"
active_tab_background = "#16455a"

red = "#ff4d6d"
yellow = "#ffc93c"
orange = "#ff9f1c"
green = "#3ff0a0"
cyan = "#5ee7ff"
blue = "#3aa9ff"
magenta = "#b06dff"
brown = "#8a5a2b"

bright_red = "#ff7b8f"
bright_yellow = "#ffe066"
bright_green = "#6bffc0"
bright_cyan = "#b6f7ff"
bright_blue = "#82ccff"
bright_magenta = "#d29bff"
